# https://scrutinizer-ci.com/docs/
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover clover.xml
            coverage:
              file: clover.xml
              format: clover
  root_path: './src/'
  environment:
    php:
      version: 7.3
      pecl_extensions:
        - swoole
  dependencies:
    override:
      - composer install --prefer-source --no-interaction
filter:
  paths:
    - src/
  dependency_paths:
    - src/vendor/
  excluded_paths:
    - src/tests/
    - src/coroutine-server.php
    - src/http-server.php
checks:
  php: true
coding_style:
  php: {  }