# https://docs.travis-ci.com/user/languages/php/
language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - yes | pecl install swoole
  - cd src
  - composer install --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit