version: '2'
services:
  php:
    image: fatindeed/vscode-remote-php
    environment:
      TIMEZONE: Asia/Shanghai
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so we will mount '..'. We'll then reference this as the
      # workspaceFolder in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/workspace

      # [Optional] If you are using SSH keys w/Git, mount your .ssh folder to
      # /root/.ssh-localhost so we can copy its contents
      - "${USERPROFILE}/.ssh:/home/vscode/.ssh-localhost:ro"

      - "${USERPROFILE}/git:/home/vscode/git:ro"
      - profile:/home/vscode/.vscode-server-insiders
volumes:
  profile:
